// Code generated by mockery v2.53.3. DO NOT EDIT.

package mock_engine

import (
	context "context"

	engine "github.com/milvus-io/milvus/internal/pkindex/core/engine"
	sst "github.com/milvus-io/milvus/internal/pkindex/core/sst"
	mock "github.com/stretchr/testify/mock"
)

// MockEngine is an autogenerated mock type for the Engine type
type MockEngine struct {
	mock.Mock
}

type MockEngine_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEngine) EXPECT() *MockEngine_Expecter {
	return &MockEngine_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function with given fields: ctx, muts
func (_m *MockEngine) Apply(ctx context.Context, muts []engine.Mutation) error {
	ret := _m.Called(ctx, muts)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []engine.Mutation) error); ok {
		r0 = rf(ctx, muts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEngine_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockEngine_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - muts []engine.Mutation
func (_e *MockEngine_Expecter) Apply(ctx interface{}, muts interface{}) *MockEngine_Apply_Call {
	return &MockEngine_Apply_Call{Call: _e.mock.On("Apply", ctx, muts)}
}

func (_c *MockEngine_Apply_Call) Run(run func(ctx context.Context, muts []engine.Mutation)) *MockEngine_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]engine.Mutation))
	})
	return _c
}

func (_c *MockEngine_Apply_Call) Return(_a0 error) *MockEngine_Apply_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEngine_Apply_Call) RunAndReturn(run func(context.Context, []engine.Mutation) error) *MockEngine_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with no fields
func (_m *MockEngine) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEngine_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockEngine_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockEngine_Expecter) Close() *MockEngine_Close_Call {
	return &MockEngine_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockEngine_Close_Call) Run(run func()) *MockEngine_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEngine_Close_Call) Return(_a0 error) *MockEngine_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEngine_Close_Call) RunAndReturn(run func() error) *MockEngine_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Destroy provides a mock function with no fields
func (_m *MockEngine) Destroy() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Destroy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEngine_Destroy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Destroy'
type MockEngine_Destroy_Call struct {
	*mock.Call
}

// Destroy is a helper method to define mock.On call
func (_e *MockEngine_Expecter) Destroy() *MockEngine_Destroy_Call {
	return &MockEngine_Destroy_Call{Call: _e.mock.On("Destroy")}
}

func (_c *MockEngine_Destroy_Call) Run(run func()) *MockEngine_Destroy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEngine_Destroy_Call) Return(_a0 error) *MockEngine_Destroy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEngine_Destroy_Call) RunAndReturn(run func() error) *MockEngine_Destroy_Call {
	_c.Call.Return(run)
	return _c
}

// DrainingGenerations provides a mock function with no fields
func (_m *MockEngine) DrainingGenerations() []engine.Generation {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DrainingGenerations")
	}

	var r0 []engine.Generation
	if rf, ok := ret.Get(0).(func() []engine.Generation); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]engine.Generation)
		}
	}

	return r0
}

// MockEngine_DrainingGenerations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DrainingGenerations'
type MockEngine_DrainingGenerations_Call struct {
	*mock.Call
}

// DrainingGenerations is a helper method to define mock.On call
func (_e *MockEngine_Expecter) DrainingGenerations() *MockEngine_DrainingGenerations_Call {
	return &MockEngine_DrainingGenerations_Call{Call: _e.mock.On("DrainingGenerations")}
}

func (_c *MockEngine_DrainingGenerations_Call) Run(run func()) *MockEngine_DrainingGenerations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEngine_DrainingGenerations_Call) Return(_a0 []engine.Generation) *MockEngine_DrainingGenerations_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEngine_DrainingGenerations_Call) RunAndReturn(run func() []engine.Generation) *MockEngine_DrainingGenerations_Call {
	_c.Call.Return(run)
	return _c
}

// DropDraining provides a mock function with given fields: ctx, gen
func (_m *MockEngine) DropDraining(ctx context.Context, gen engine.Generation) error {
	ret := _m.Called(ctx, gen)

	if len(ret) == 0 {
		panic("no return value specified for DropDraining")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, engine.Generation) error); ok {
		r0 = rf(ctx, gen)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEngine_DropDraining_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DropDraining'
type MockEngine_DropDraining_Call struct {
	*mock.Call
}

// DropDraining is a helper method to define mock.On call
//   - ctx context.Context
//   - gen engine.Generation
func (_e *MockEngine_Expecter) DropDraining(ctx interface{}, gen interface{}) *MockEngine_DropDraining_Call {
	return &MockEngine_DropDraining_Call{Call: _e.mock.On("DropDraining", ctx, gen)}
}

func (_c *MockEngine_DropDraining_Call) Run(run func(ctx context.Context, gen engine.Generation)) *MockEngine_DropDraining_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(engine.Generation))
	})
	return _c
}

func (_c *MockEngine_DropDraining_Call) Return(_a0 error) *MockEngine_DropDraining_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEngine_DropDraining_Call) RunAndReturn(run func(context.Context, engine.Generation) error) *MockEngine_DropDraining_Call {
	_c.Call.Return(run)
	return _c
}

// FlushDraining provides a mock function with given fields: ctx, gen
func (_m *MockEngine) FlushDraining(ctx context.Context, gen engine.Generation) ([]sst.Info, error) {
	ret := _m.Called(ctx, gen)

	if len(ret) == 0 {
		panic("no return value specified for FlushDraining")
	}

	var r0 []sst.Info
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, engine.Generation) ([]sst.Info, error)); ok {
		return rf(ctx, gen)
	}
	if rf, ok := ret.Get(0).(func(context.Context, engine.Generation) []sst.Info); ok {
		r0 = rf(ctx, gen)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sst.Info)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, engine.Generation) error); ok {
		r1 = rf(ctx, gen)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEngine_FlushDraining_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlushDraining'
type MockEngine_FlushDraining_Call struct {
	*mock.Call
}

// FlushDraining is a helper method to define mock.On call
//   - ctx context.Context
//   - gen engine.Generation
func (_e *MockEngine_Expecter) FlushDraining(ctx interface{}, gen interface{}) *MockEngine_FlushDraining_Call {
	return &MockEngine_FlushDraining_Call{Call: _e.mock.On("FlushDraining", ctx, gen)}
}

func (_c *MockEngine_FlushDraining_Call) Run(run func(ctx context.Context, gen engine.Generation)) *MockEngine_FlushDraining_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(engine.Generation))
	})
	return _c
}

func (_c *MockEngine_FlushDraining_Call) Return(_a0 []sst.Info, _a1 error) *MockEngine_FlushDraining_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEngine_FlushDraining_Call) RunAndReturn(run func(context.Context, engine.Generation) ([]sst.Info, error)) *MockEngine_FlushDraining_Call {
	_c.Call.Return(run)
	return _c
}

// GetLocalMeta provides a mock function with given fields: key
func (_m *MockEngine) GetLocalMeta(key string) ([]byte, bool, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetLocalMeta")
	}

	var r0 []byte
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, bool, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(key)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockEngine_GetLocalMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLocalMeta'
type MockEngine_GetLocalMeta_Call struct {
	*mock.Call
}

// GetLocalMeta is a helper method to define mock.On call
//   - key string
func (_e *MockEngine_Expecter) GetLocalMeta(key interface{}) *MockEngine_GetLocalMeta_Call {
	return &MockEngine_GetLocalMeta_Call{Call: _e.mock.On("GetLocalMeta", key)}
}

func (_c *MockEngine_GetLocalMeta_Call) Run(run func(key string)) *MockEngine_GetLocalMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockEngine_GetLocalMeta_Call) Return(_a0 []byte, _a1 bool, _a2 error) *MockEngine_GetLocalMeta_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockEngine_GetLocalMeta_Call) RunAndReturn(run func(string) ([]byte, bool, error)) *MockEngine_GetLocalMeta_Call {
	_c.Call.Return(run)
	return _c
}

// InstallBaseline provides a mock function with given fields: ctx, tables
func (_m *MockEngine) InstallBaseline(ctx context.Context, tables []engine.BaselineTable) error {
	ret := _m.Called(ctx, tables)

	if len(ret) == 0 {
		panic("no return value specified for InstallBaseline")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []engine.BaselineTable) error); ok {
		r0 = rf(ctx, tables)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEngine_InstallBaseline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallBaseline'
type MockEngine_InstallBaseline_Call struct {
	*mock.Call
}

// InstallBaseline is a helper method to define mock.On call
//   - ctx context.Context
//   - tables []engine.BaselineTable
func (_e *MockEngine_Expecter) InstallBaseline(ctx interface{}, tables interface{}) *MockEngine_InstallBaseline_Call {
	return &MockEngine_InstallBaseline_Call{Call: _e.mock.On("InstallBaseline", ctx, tables)}
}

func (_c *MockEngine_InstallBaseline_Call) Run(run func(ctx context.Context, tables []engine.BaselineTable)) *MockEngine_InstallBaseline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]engine.BaselineTable))
	})
	return _c
}

func (_c *MockEngine_InstallBaseline_Call) Return(_a0 error) *MockEngine_InstallBaseline_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEngine_InstallBaseline_Call) RunAndReturn(run func(context.Context, []engine.BaselineTable) error) *MockEngine_InstallBaseline_Call {
	_c.Call.Return(run)
	return _c
}

// Probe provides a mock function with given fields: ctx, keys
func (_m *MockEngine) Probe(ctx context.Context, keys [][]byte) ([][]byte, error) {
	ret := _m.Called(ctx, keys)

	if len(ret) == 0 {
		panic("no return value specified for Probe")
	}

	var r0 [][]byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, [][]byte) ([][]byte, error)); ok {
		return rf(ctx, keys)
	}
	if rf, ok := ret.Get(0).(func(context.Context, [][]byte) [][]byte); ok {
		r0 = rf(ctx, keys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, [][]byte) error); ok {
		r1 = rf(ctx, keys)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEngine_Probe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Probe'
type MockEngine_Probe_Call struct {
	*mock.Call
}

// Probe is a helper method to define mock.On call
//   - ctx context.Context
//   - keys [][]byte
func (_e *MockEngine_Expecter) Probe(ctx interface{}, keys interface{}) *MockEngine_Probe_Call {
	return &MockEngine_Probe_Call{Call: _e.mock.On("Probe", ctx, keys)}
}

func (_c *MockEngine_Probe_Call) Run(run func(ctx context.Context, keys [][]byte)) *MockEngine_Probe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([][]byte))
	})
	return _c
}

func (_c *MockEngine_Probe_Call) Return(_a0 [][]byte, _a1 error) *MockEngine_Probe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEngine_Probe_Call) RunAndReturn(run func(context.Context, [][]byte) ([][]byte, error)) *MockEngine_Probe_Call {
	_c.Call.Return(run)
	return _c
}

// PutLocalMeta provides a mock function with given fields: key, val
func (_m *MockEngine) PutLocalMeta(key string, val []byte) error {
	ret := _m.Called(key, val)

	if len(ret) == 0 {
		panic("no return value specified for PutLocalMeta")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(key, val)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEngine_PutLocalMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutLocalMeta'
type MockEngine_PutLocalMeta_Call struct {
	*mock.Call
}

// PutLocalMeta is a helper method to define mock.On call
//   - key string
//   - val []byte
func (_e *MockEngine_Expecter) PutLocalMeta(key interface{}, val interface{}) *MockEngine_PutLocalMeta_Call {
	return &MockEngine_PutLocalMeta_Call{Call: _e.mock.On("PutLocalMeta", key, val)}
}

func (_c *MockEngine_PutLocalMeta_Call) Run(run func(key string, val []byte)) *MockEngine_PutLocalMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte))
	})
	return _c
}

func (_c *MockEngine_PutLocalMeta_Call) Return(_a0 error) *MockEngine_PutLocalMeta_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEngine_PutLocalMeta_Call) RunAndReturn(run func(string, []byte) error) *MockEngine_PutLocalMeta_Call {
	_c.Call.Return(run)
	return _c
}

// RotateIncrement provides a mock function with given fields: ctx
func (_m *MockEngine) RotateIncrement(ctx context.Context) (engine.Generation, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RotateIncrement")
	}

	var r0 engine.Generation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (engine.Generation, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) engine.Generation); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(engine.Generation)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEngine_RotateIncrement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RotateIncrement'
type MockEngine_RotateIncrement_Call struct {
	*mock.Call
}

// RotateIncrement is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEngine_Expecter) RotateIncrement(ctx interface{}) *MockEngine_RotateIncrement_Call {
	return &MockEngine_RotateIncrement_Call{Call: _e.mock.On("RotateIncrement", ctx)}
}

func (_c *MockEngine_RotateIncrement_Call) Run(run func(ctx context.Context)) *MockEngine_RotateIncrement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockEngine_RotateIncrement_Call) Return(_a0 engine.Generation, _a1 error) *MockEngine_RotateIncrement_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEngine_RotateIncrement_Call) RunAndReturn(run func(context.Context) (engine.Generation, error)) *MockEngine_RotateIncrement_Call {
	_c.Call.Return(run)
	return _c
}

// Stats provides a mock function with no fields
func (_m *MockEngine) Stats() engine.Stats {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 engine.Stats
	if rf, ok := ret.Get(0).(func() engine.Stats); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(engine.Stats)
	}

	return r0
}

// MockEngine_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockEngine_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
func (_e *MockEngine_Expecter) Stats() *MockEngine_Stats_Call {
	return &MockEngine_Stats_Call{Call: _e.mock.On("Stats")}
}

func (_c *MockEngine_Stats_Call) Run(run func()) *MockEngine_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEngine_Stats_Call) Return(_a0 engine.Stats) *MockEngine_Stats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEngine_Stats_Call) RunAndReturn(run func() engine.Stats) *MockEngine_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEngine creates a new instance of MockEngine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEngine(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEngine {
	mock := &MockEngine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
