autoindex:
  params:
    search: ""
    tuning: ""
common:
  bloomfiltersize: 100000
  buildindexthreadpoolratio: 0.75
  defaultindexname: _default_idx
  defaultpartitionname: _default
  diskindex:
    beamwidthratio: 4
    buildnumthreadsratio: 1
    loadnumthreadratio: 8
    maxdegree: 56
    pqcodebudgetgbratio: 0.125
    searchcachebudgetgbratio: 0.1
    searchlistsize: 100
  entityexpiration: -1
  gracefulstoptimeout: 1800
  gracefultime: 5000
  indexslicesize: 16
  locks:
    metrics:
      enable: false
    threshold:
      info: 500
      warn: 1000
  maxbloomfalsepositive: 0.001
  security:
    authorizationenabled: false
    tlsmode: 0
  session:
    retrytimes: 30
    ttl: 30
  simdtype: auto
  storage:
    enablev2: false
    scheme: s3
  storagetype: remote
  threadcorecoefficient:
    highpriority: 10
    lowpriority: 1
    middlepriority: 5
  tracelogmode: 0
  ttmsgenabled: true
datacoord:
  autobalance: true
  autoupgradesegmentindex: false
  brokertimeout: 5000
  channel:
    balanceinterval: 360
    balancesilentduration: 300
    balancewithrpc: true
    checkinterval: 1
    legacyversionwithoutrpcwatch: 2.4.0
    notifychanneloperationtimeout: 5
    watchtimeoutinterval: 300
  checkautobalanceconfiginterval: 10
  compaction:
    enableautocompaction: true
    indexbasedcompaction: true
    levelzero:
      forcetrigger:
        deltalogmaxnum: 30
        deltalogminnum: 10
        maxsize: 67108864
        minsize: 8388608
    maxparalleltasknum: 10
    rpctimeout: 10
    workermaxparalleltasknum: 2
  enableactivestandby: false
  enablecompaction: true
  enablegarbagecollection: true
  gc:
    droptolerance: 10800
    interval: 3600
    missingtolerance: 86400
    removeconcurrent: 32
    scaninterval: 168
  gracefulstoptimeout: 5
  grpc:
    clientmaxrecvsize: 536870912
    clientmaxsendsize: 268435456
    servermaxrecvsize: 268435456
    servermaxsendsize: 536870912
  import:
    checkintervalhigh: 2
    checkintervallow: 120
    filesperpreimporttask: 2
    maximportfilenumperreq: 1024
    maxsizeinmbperimporttask: 6144
    scheduleinterval: 2
    taskretention: 10800
    waitforindex: true
  port: 13333
  segment:
    alloclatestexpireattempt: 200
    assignmentexpiration: 2000
    compactableproportion: 0.85
    disksegmentmaxsize: 2048
    expansionrate: 1.25
    maxbinlogfilenumber: 32
    maxidletime: 600
    maxlife: 86400
    maxsize: 1024
    minsizefromidletosealed: 16
    sealproportion: 0.12
    smallproportion: 0.5
datanode:
  channel:
    channelcheckpointupdatetickinseconds: 10
    maxchannelcheckpointsperprc: 128
    updatechannelcheckpointinterval: 60
    updatechannelcheckpointmaxparallel: 10
    updatechannelcheckpointrpctimeout: 20
    workpoolsize: -1
  compaction:
    levelzerobatchmemoryratio: 0.05
  datasync:
    flowgraph:
      maxparallelism: 1024
      maxqueuelength: 16
    maxparallelsyncmgrtasks: 256
    skipmode:
      coldtime: 60
      enable: true
      skipnum: 4
  gracefulstoptimeout: 1800
  grpc:
    clientmaxrecvsize: 536870912
    clientmaxsendsize: 268435456
    servermaxrecvsize: 268435456
    servermaxsendsize: 536870912
  import:
    maxconcurrenttasknum: 16
    maximportfilesizeingb: 16
    readbuffersizeinmb: 16
  memory:
    checkinterval: 3000
    forcesyncenable: true
    forcesyncsegmentnum: 1
    forcesyncwatermark: 0.5
  port: 21124
  segment:
    deletebufbytes: 67108864
    insertbufsize: 16777216
    syncperiod: 600
  slot:
    slotcap: 2
  timetick:
    byrpc: true
    interval: 500
etcd:
  auth:
    enabled: false
  data:
    dir: default.etcd
  endpoints: localhost:2379
  kvsubpath: kv
  log:
    level: info
    path: stdout
  metasubpath: meta
  requesttimeout: 10000
  rootpath: by-dev
  ssl:
    enabled: false
    tlscacert: /path/to/ca.pem
    tlscert: /path/to/etcd-client.pem
    tlskey: /path/to/etcd-client-key.pem
    tlsminversion: 1.3
  use:
    embed: false
grpc:
  client:
    compressionenabled: false
    dialtimeout: 200
    initialbackoff: 0.2
    keepalivetime: 10000
    keepalivetimeout: 20000
    maxbackoff: 10
    maxcancelerror: 32
    maxmaxattempts: 10
    minresetinterval: 1000
    minsessioncheckinterval: 200
  gracefulstoptimeout: 10
  log:
    level: WARNING
indexcoord:
  bindindexnodemode:
    address: localhost:22930
    enable: false
    nodeid: 0
    withcred: false
  segment:
    minsegmentnumrowstoenableindex: 1024
indexnode:
  enabledisk: true
  grpc:
    clientmaxrecvsize: 536870912
    clientmaxsendsize: 268435456
    servermaxrecvsize: 268435456
    servermaxsendsize: 536870912
  maxdiskusagepercentage: 95
  port: 21121
  scheduler:
    buildparallel: 1
localstorage:
  path: /tmp/milvus/data/
log:
  file:
    maxage: 10
    maxbackups: 20
    maxsize: 300
  format: text
  level: info
  stdout: true
metastore:
  type: etcd
minio:
  accesskeyid: minioadmin
  address: localhost
  bucketname: a-bucket
  cloudprovider: aws
  listobjectsmaxkeys: 0
  loglevel: fatal
  port: 9000
  requesttimeoutms: 10000
  rootpath: files
  secretaccesskey: minioadmin
  ssl:
    tlscacert: /path/to/public.crt
  useiam: false
  usessl: false
  usevirtualhost: false
mq:
  enablepursuitmode: true
  mqbufsize: 16
  pursuitbuffersize: 8388608
  pursuitlag: 10
  type: default
natsmq:
  server:
    initializetimeout: 4000
    maxfilestore: 17179869184
    maxpayload: 8388608
    maxpending: 67108864
    monitor:
      debug: false
      logfile: /tmp/milvus/logs/nats.log
      logsizelimit: 536870912
      logtime: true
      trace: false
    port: 4222
    retention:
      maxage: 4320
    storedir: /var/lib/milvus/nats
proxy:
  accesslog:
    cachesize: 10240
    enable: false
    formatters:
      base:
        format: '[$time_now] [ACCESS] <$user_name: $user_addr> $method_name [status:
          $method_status] [code: $error_code] [sdk: $sdk_version] [msg: $error_msg]
          [traceID: $trace_id] [timeCost: $time_cost]'
      query:
        format: '[$time_now] [ACCESS] <$user_name: $user_addr> $method_name [status:
          $method_status] [code: $error_code] [sdk: $sdk_version] [msg: $error_msg]
          [traceID: $trace_id] [timeCost: $time_cost] [database: $database_name] [collection:
          $collection_name] [partitions: $partition_name] [expr: $method_expr]'
        methods: Query,Search,Delete
    localpath: /tmp/milvus_access
    maxsize: 64
    minioenable: false
    remotemaxtime: 0
    remotepath: access_log/
    rotatedtime: 0
  connectioncheckintervalseconds: 120
  connectionclientinfottlseconds: 86400
  ginlogging: true
  ginlogskippaths: /
  gracefulstoptimeout: 30
  grpc:
    clientmaxrecvsize: 67108864
    clientmaxsendsize: 268435456
    servermaxrecvsize: 67108864
    servermaxsendsize: 268435456
  healthchecktimeout: 3000
  http:
    accepttypeallowint64: true
    debug_mode: false
    enabled: true
    enablepprof: true
  internalport: 19529
  maxconnectionnum: 10000
  maxdimension: 32768
  maxfieldnum: 64
  maxnamelength: 255
  maxshardnum: 16
  maxtasknum: 1024
  maxvectorfieldnum: 4
  msgstream:
    timetick:
      bufsize: 512
  mustusepartitionkey: false
  port: 19530
  slowqueryspaninseconds: 5
  timetickinterval: 200
pulsar:
  address: localhost
  enableclientmetrics: false
  maxmessagesize: 5242880
  namespace: default
  port: 6650
  requesttimeout: 60
  tenant: public
  webport: 80
querycoord:
  autobalance: true
  autobalancechannel: true
  autohandoff: true
  balancecostthreshold: 0.001
  balanceintervalseconds: 60
  balancer: ScoreBasedBalancer
  brokertimeout: 5000
  channelexclusivenodefactor: 4
  channeltasktimeout: 60000
  checkautobalanceconfiginterval: 10
  checkbalanceinterval: 10000
  checkchannelinterval: 1000
  checkhandoffinterval: 5000
  checkhealthinterval: 3000
  checkhealthrpctimeout: 2000
  checkindexinterval: 10000
  checkinterval: 1000
  checknodesessioninterval: 60
  checksegmentinterval: 1000
  cleanexcludesegmentinterval: 60
  collectionrecovertimes: 3
  distpullinterval: 500
  distrequesttimeout: 5000
  enableactivestandby: false
  enablestoppingbalance: true
  globalrowcountfactor: 0.1
  globalsegmentcountfactor: 0.1
  gracefulstoptimeout: 5
  growingrowcountweight: 4
  grpc:
    clientmaxrecvsize: 536870912
    clientmaxsendsize: 268435456
    servermaxrecvsize: 268435456
    servermaxsendsize: 536870912
  heartbeatavailableinterval: 10000
  heatbeatwarninglag: 5000
  loadtimeoutseconds: 600
  memoryusagemaxdifferencepercentage: 30
  observertaskparallel: 16
  overloadedmemorythresholdpercentage: 90
  port: 19531
  randommaxsteps: 10
  reverseunbalancetolerationfactor: 1.3
  rowcountfactor: 0.4
  rowcountmaxsteps: 50
  scoreunbalancetolerationfactor: 0.05
  segmentcountfactor: 0.4
  segmentcountmaxsteps: 50
  segmenttasktimeout: 120000
  taskexecutioncap: 256
  taskmergecap: 1
querynode:
  cache:
    enabled: true
    memorylimit: 2147483648
    readaheadpolicy: willneed
    warmup: false
  datasync:
    flowgraph:
      maxparallelism: 1024
      maxqueuelength: 16
  enabledisk: false
  enablesegmentprune: false
  grouping:
    enabled: true
    maxnq: 1000
    topkmergeratio: 20
  grpc:
    clientmaxrecvsize: 536870912
    clientmaxsendsize: 268435456
    servermaxrecvsize: 268435456
    servermaxsendsize: 536870912
  lazyload:
    enabled: false
    maxevictperretry: 1
    maxretrytimes: 1
    requestresourceretryinterval: 2000
    requestresourcetimeout: 5000
    waittimeout: 30000
  loadmemoryusagefactor: 1
  maxdiskusagepercentage: 95
  mmap:
    mmapenabled: false
  port: 21123
  scheduler:
    cpuratio: 10
    maxreadconcurrentratio: 1
    maxtimestamplag: 86400
    receivechansize: 10240
    schedulereadpolicy:
      enablecrossusergrouping: false
      maxpendingtaskperuser: 1024
      name: fifo
      taskqueueexpire: 60
    unsolvedqueuesize: 10240
  segcore:
    chunkrows: 128
    interimindex:
      buildparallelrate: 0.5
      enableindex: true
      memexpansionrate: 1.15
      nlist: 128
      nprobe: 16
    knowherescoreconsistency: false
    knowherethreadpoolnumratio: 4
  stats:
    publishinterval: 1000
quotaandlimits:
  compactionrate:
    db:
      max: -1
    enabled: false
    max: -1
  ddl:
    collectionrate: -1
    db:
      collectionrate: -1
      partitionrate: -1
    enabled: false
    partitionrate: -1
  dml:
    bulkloadrate:
      collection:
        max: -1
      db:
        max: -1
      max: -1
      partition:
        max: -1
    deleterate:
      collection:
        max: -1
      db:
        max: -1
      max: -1
      partition:
        max: -1
    enabled: false
    insertrate:
      collection:
        max: -1
      db:
        max: -1
      max: -1
      partition:
        max: -1
    upsertrate:
      collection:
        max: -1
      db:
        max: -1
      max: -1
      partition:
        max: -1
  dql:
    enabled: false
    queryrate:
      collection:
        max: -1
      db:
        max: -1
      max: -1
      partition:
        max: -1
    searchrate:
      collection:
        max: -1
      db:
        max: -1
      max: -1
      partition:
        max: -1
  enabled: true
  flushrate:
    collection:
      max: -1
    db:
      max: -1
    enabled: false
    max: -1
  indexrate:
    db:
      max: -1
    enabled: false
    max: -1
  limitreading:
    cooloffspeed: 0.9
    forcedeny: false
    queueprotection:
      enabled: false
      nqinqueuethreshold: -1
      queuelatencythreshold: -1
    resultprotection:
      enabled: false
      maxreadresultrate: -1
      maxreadresultratepercollection: -1
      maxreadresultrateperdb: -1
  limits:
    allocretrytimes: 15
    allocwaitinterval: 1000
    complexdeletelimitenable: false
    maxcollectionnum: 65536
    maxcollectionnumperdb: 65536
    maxinsertsize: -1
    maxresourcegroupnumofquerynode: 1024
  limitwriting:
    diskprotection:
      diskquota: -1
      diskquotapercollection: -1
      diskquotaperdb: -1
      diskquotaperpartition: -1
      enabled: true
    forcedeny: false
    growingsegmentssizeprotection:
      enabled: false
      highwaterlevel: 0.4
      lowwaterlevel: 0.2
      minrateratio: 0.5
    memprotection:
      datanodememoryhighwaterlevel: 0.95
      datanodememorylowwaterlevel: 0.85
      enabled: true
      querynodememoryhighwaterlevel: 0.95
      querynodememorylowwaterlevel: 0.85
    ttprotection:
      enabled: false
      maxtimetickdelay: 300
  quotacentercollectinterval: 3
rocksmq:
  compactioninterval: 86400
  compressiontypes: 0,0,7,7,7
  lrucacheratio: 0.06
  path: /var/lib/milvus/rdb_data
  retentionsizeinmb: 8192
  retentiontimeinminutes: 4320
  rocksmqpagesize: 67108864
rootcoord:
  dmlchannelnum: 16
  enableactivestandby: false
  gracefulstoptimeout: 5
  grpc:
    clientmaxrecvsize: 536870912
    clientmaxsendsize: 268435456
    servermaxrecvsize: 268435456
    servermaxsendsize: 536870912
  maxdatabasenum: 64
  maxgeneralcapacity: 65536
  maxpartitionnum: 4096
  minsegmentsizetoenableindex: 1024
  port: 53100
tikv:
  endpoints: 127.0.0.1:2389
  kvsubpath: kv
  metasubpath: meta
  requesttimeout: 10000
  rootpath: by-dev
  snapshotscansize: 256
  ssl:
    enabled: false
tls:
  capempath: configs/cert/ca.pem
  serverkeypath: configs/cert/server.key
  serverpempath: configs/cert/server.pem
trace:
  exporter: noop
  otlp:
    secure: true
  samplefraction: 0
